-- You can use this file to load seed data into the database using SQL statements
insert into Member (id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212');

INSERT INTO USER (USER_ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, AGE, GENDER, ACADEMIC_DEGREE) VALUES (0, 'Susana', 'Gonçalves', '123456', 'susana.goncalves@portugalmail.pt', 38, 'feminino', 'licenciatura');
INSERT INTO USER (USER_ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, AGE, GENDER, ACADEMIC_DEGREE) VALUES (9999999, 'Arthur', 'Portas', '123456', 'arthurportas@gmail.com', 35, 'masculino', 'licenciatura');
INSERT INTO USER (USER_ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, AGE, GENDER, ACADEMIC_DEGREE) VALUES (1000000, 'demo', 'demo', 'demo', 'demo@example.com', 20, 'masculino', 'licenciatura');

INSERT INTO ROLE (ROLE_ID, NAME, USER_ID_FK) VALUES(1, 'Professor', 0);
INSERT INTO ROLE (ROLE_ID, NAME, USER_ID_FK) VALUES(2, 'Diretor', 0);
INSERT INTO ROLE (ROLE_ID, NAME, USER_ID_FK) VALUES(3, 'Outra', 0);

--Quiz
INSERT INTO QUIZ (QUIZ_ID, DESCRIPTION) VALUES (0, 'Demo');

--Level
INSERT INTO LEVEL (LEVEL_ID, DESCRIPTION, QUIZ_ID_FK) VALUES (1, 'Alfabetização Tecnológica', 0);
INSERT INTO LEVEL (LEVEL_ID, DESCRIPTION, QUIZ_ID_FK) VALUES (2, 'Aprofundamento do Conhecimento', 0);
INSERT INTO LEVEL (LEVEL_ID, DESCRIPTION, QUIZ_ID_FK) VALUES (3, 'Criação de Conhecimento', 0);

--LEVEL 1 - DOMAINS
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (1, 'Compreensão das TIC na educação', 1);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (2, 'Currículo e Avaliação', 1);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (3, 'Pedagogia', 1);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (4, 'TIC', 1);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (5, 'Organização e Administração', 1);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (6, 'Desenvolvimento Profissional Docente', 1);
--LEVEL 2 - DOMAINS
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (7, 'Compreensão das TIC na educação', 2);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (8, 'Currículo e Avaliação', 2);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (9, 'Pedagogia', 2);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (10, 'TIC', 2);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (11, 'Organização e Administração', 2);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (12, 'Desenvolvimento Profissional Docente', 2);
--LEVEL 3 - DOMAINS
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (13, 'Compreensão das TIC na educação', 3);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (14, 'Currículo e Avaliação', 3);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (15, 'Pedagogia', 3);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (16, 'TIC', 3);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (17, 'Organização e Administração', 3);
INSERT INTO DOMAIN (DOMAIN_ID, DESCRIPTION, LEVEL_ID_FK) VALUES (18, 'Desenvolvimento Profissional Docente', 3);


INSERT INTO RESULT (RESULT_ID, RESULT_VALUE, QUIZ_ID_FK) VALUES(1, '1.0', 0);
INSERT INTO RESULT (RESULT_ID, RESULT_VALUE, QUIZ_ID_FK) VALUES(2, '1.0', 0);
INSERT INTO RESULT (RESULT_ID, RESULT_VALUE, QUIZ_ID_FK) VALUES(3, '1.0', 0);

--##LEVEL 1-'Alfabetização Tecnológica'
--Domain 1 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (1, 'Capaz de identificar as principais características das práticas de sala de aula e especificar como essas características servem para implementar as políticas de integração das TIC em contexto de sala de aula', 1);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(1, 'R1P1', '0', 1);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(2, 'R2P1', '0.33', 1);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(3, 'R3P1', '0.66', 1);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(4, 'R4P1', '1', 1);

--Domain 2 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (2, 'Capaz de combinar padrões curriculares específicos com pacotes de software específicos e aplicações informáticas e descrever como esses padrões são sustentados por essas aplicações', 2);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(5, 'R1P2', '0', 2);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(6, 'R2P2', '0.33', 2);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(7, 'R3P2', '0.66', 2);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(8, 'R4P2', '1', 2);
--Domain 3 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (3, 'Sou capaz de descrever como o ensino didático e as TIC podem ser utilizados para apoiar na aquisição de conhecimentos escolar sobre a disciplina', 3);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(9, 'R1P3', '0', 3);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(10, 'R2P3', '0.33', 3);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(11, 'R3P3', '0.66', 3);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(12, 'R4P3', '1', 3);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (4, 'Sou capaz de incorporar atividades  apropriadas de TIC em planos de aula, de modo a apoiar a aquisição de conhecimentos escolar sobre a disciplina', 3);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(13, 'R1P4', '0', 4);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(14, 'R2P4', '0.33', 4);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(15, 'R3P4', '0.66', 4);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(16, 'R4P4', '1', 4);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (5, 'Utilizo software de apresentação e recursos digitais para apoiar as aulas', 3);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(17, 'R1P5', '0', 5);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(18, 'R2P5', '0.33', 5);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(19, 'R3P5', '0.66', 5);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(20, 'R4P5', '1', 5);


--Domain 4 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (6, 'Sou capaz de descrever e demonstrar a utilização de hardware comum', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(21, 'R1P6', '0', 6);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(22, 'R2P6', '0.33', 6);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(23, 'R3P6', '0.66', 6);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(24, 'R4P6', '1', 6);


INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (7, 'Descrever e demonstrar as tarefas básicas e aplicações de processadores de texto, como a entrada de texto, edição de texto, formatação de texto e impressão', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(25, 'R1P7', '0', 7);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(26, 'R2P7', '0.33', 7);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(27, 'R3P7', '0.66', 7);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(28, 'R4P7', '1', 7);


INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (8, 'Descrever e demonstrar a finalidade e características básicas do software de apresentação e outros recursos digitais', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(29, 'R1P8', '0', 8);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(30, 'R2P8', '0.33', 8);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(31, 'R3P8', '0.66' , 8);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(32, 'R4P8', '1', 8);


INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (9, 'Descrever o propósito e a função básica do software gráfico e usar um pacote de software de gráficos para criar um display gráfico simples', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(33, 'R1P9', '0', 9);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(34, 'R2P9', '0.33', 9);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(35, 'R3P9', '0.66', 9);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(36, 'R4P9', '1', 9);


INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (10, 'Descrever a Internet e a World Wide Web, refletir sobre os seus usos, descrever como funciona um browser e usar uma URL para aceder a um site', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(37, 'R1P10', '0', 10);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(38, 'R2P10', '0.33', 10);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(39, 'R3P10', '0.66', 10);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(40, 'R4P10', '1', 10);


INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (11, 'Utilizar um motor de busca', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(41, 'R1P11', '0', 11);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(42, 'R2P11', '0.33', 11);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(43, 'R3P11', '0.66', 11);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(44, 'R4P11', '1', 11);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (12, 'Criar uma conta de e-mail e utilizá-la para criar uma cadeia de correspondência de e-mails', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(45, 'R1P12', '0', 12);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(46, 'R2P12', '0.33', 12);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(47, 'R3P12', '0.66', 12);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(48, 'R4P12', '1', 12);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (13, 'Descrever as funcionalidades e os propósito dos tutoriais e software de treino e a forma como apoia os alunos na aquisição de conhecimentos escolares sobre a disciplina', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(49, 'R1P13', '0', 13);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(50, 'R2P13', '0.33', 13);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(51, 'R3P13', '0.66', 13);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(52, 'R4P13', '1', 13);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (14, 'Localizar pacotes de software educacional e recursos da web prontos para serem utilizados, avaliá-los no que diz respeito à sua precisão e alinhamento com os padrões curriculares e combiná-los com as necessidades específicas dos alunos', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(53, 'R1P14', '0', 14);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(54, 'R2P14', '0.33', 14);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(55, 'R3P14', '0.66', 14);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(56, 'R4P14', '1', 14);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (15, 'Usar software online de manutenção de registros para marcar presenças, submeter notas e manter os registos dos alunos', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(57, 'R1P15', '0', 15);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(58, 'R2P15', '0.33', 15);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(59, 'R3P15', '0.66', 15);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(60, 'R4P15', '1', 15);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (16, 'Usar tecnologias de colaboração e comunicação, tais como mensagens de texto, videoconferância e colaboração baseada na web e em ambientes sociais', 4);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(61, 'R1P16', '0', 16);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(62, 'R2P16', '0.33', 16);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(63, 'R3P16', '0.66', 16);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(64, 'R4P16', '1', 16);

--Domain 5 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (17, 'Integrar o uso de um laboratório de informática em atividades de ensino em curso', 5);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(65, 'R1P17', '0', 17);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(66, 'R2P17', '0.33', 17);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(67, 'R3P17', '0.66', 17);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(68, 'R4P17', '1', 17);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (18, 'Gerir o uso de recursos suplementares de TIC com indivíduos e pequenos grupos de alunos em sala de aula regular, de modo a não perturbar outras atividades de ensino na turma', 5);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(69, 'R1P18', '0', 18);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(70, 'R2P18', '0.33', 18);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(71, 'R3P18', '0.66', 18);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(72, 'R4P18', '1', 18);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (19, 'Identificar as organizações sociais apropriadas e inapropriadas para o uso de várias tecnologias', 5);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(73, 'R1P19', '0', 19);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(74, 'R2P19', '0.33', 19);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(75, 'R3P19', '0.66', 19);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(76, 'R4P19', '1', 19);

--Domain 6 - QUEST
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (20, 'Usar os recursos TIC para melhorar a sua produtividade', 6);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(77, 'R1P20', '0', 20);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(78, 'R2P20', '0.33', 20);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(79, 'R3P20', '0.66', 20);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(80, 'R4P20', '1', 20);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (21, 'Usar os recursos TIC para apoiar a sua própria aquisição de matéria e de conhecimento pedagógico', 6);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(81, 'R1P21', '0', 21);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(82, 'R2P21', '0.33', 21);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(83, 'R3P21', '0.66', 21);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(84, 'R4P21', '1', 21);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (22, 'Identificar e gerir problemas de segurança da Internet', 6);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(85, 'R1P22', '0', 22);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(86, 'R2P22', '0.33', 22);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(87, 'R3P22', '0.66', 22);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(88, 'R4P22', '1', 22);

--##LEVEL 2-'Aprofundamento do Conhecimento'
--Domain 1 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (23, 'Capaz de explicar e analisar os princípios de utilização das TIC na educação, descrevendo como esses princípios podem ser postos em prática no ensino, e analisa os problemas que surgem na implementação desses princípios e como podem ser resolvidos', 7);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(89, 'R1P23', '0', 23);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(90, 'R2P23', '0.33', 23);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(91, 'R3P23', '0.66', 23);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(92, 'R4P23', '1', 23);

--Domain 2 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (24, 'Identificar os principais conceitos e processos nas áreas de conteúdo; descrever a função e o propósito das ferramentas específicas das disciplinas e  de que forma  podem ajudar no entendimento, por parte dos alunos, desses conceitos-chave e processos e sua aplicação ao mundo fora da sala de aula', 8);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(93, 'R1P24', '0', 24);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(94, 'R2P24', '0.33', 24);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(95, 'R3P24', '0.66', 24);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(96, 'R4P24', '1', 24);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (25, 'O professor é capaz de desenvolver e aplicar regras com base em conhecimento e desempenho que permitam que os professores avaliem  a compreensão dos alunos sobre conceitos-chave das matérias, competências e processos', 8);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(97, 'R1P25', '0', 25);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(98, 'R2P25', '0.33', 25);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(99, 'R3P25', '0.66', 25);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(100, 'R4P25', '1', 25);

--Domain 3 
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (26, 'Descrever a forma como a aprendizagem colaborativa baseada em projectos e as TIC podem apoiar o pensamento e a interacão social dos alunos, já que os alunos compreendem conceitos-chave, processos e competências na disciplina e utilizam-nos para resolver problemas do mundo real', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(101, 'R1P26', '0', 26);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(102, 'R2P26', '0.33', 26);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(103, 'R3P26', '0.66', 26);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(104, 'R4P26', '1', 26);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (27, 'Identificar ou elaborar  problemas complexos do mundo real e estruturá-los de uma forma a incorporar os principais conceitos da matéria e servir como base para projetos do aluno', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(105, 'R1P27', '0', 27);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(106, 'R2P27', '0.33', 27);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(107, 'R3P27', '0.66', 27);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(108, 'R4P27', '1', 27);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (28, 'Elaborar materiais on-line que apoiem o melhor entendimento dos alunos sobre os principais conceitos e sua aplicação no mundo real', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(109, 'R1P28', '0', 28);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(110, 'R2P28', '0.33', 28);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(111, 'R3P28', '0.66', 28);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(112, 'R4P28', '1', 28);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (29, 'Elaborar planos de aula e actividades em sala de aula para que os alunos se envolvam na discussão, debate e no uso dos principais conceitos da matéria enquanto colaboram para compreender, representar e solucionar problemas complexos do mundo real, assim como reflectir sobre as soluções e informá-las', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(113, 'R1P29', '0', 29);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(114, 'R2P29', '0.33', 29);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(115, 'R3P29', '0.66', 29);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(116, 'R4P29', '1', 29);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (30, 'Estruturar planificações e actividades de sala de aula de modo que as ferramentas abertas e aplicativos específicos da matéria ajudem os alunos na discussão, debate e no uso dos conceitos da disciplina e dos processos, enquanto colaboram para solucionar problemas complexos', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(117, 'R1P30', '0', 30);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(118, 'R2P30', '0.33', 30);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(119, 'R3P30', '0.66', 30);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(120, 'R4P30', '1', 30);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (31, 'Implementar planificações e actividades em sala de aula colaborativas e com base em projecto, enquanto orientam os alunos à boa finalização e profundo entendimento dos seus projectos e conceitos-chave', 9);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(121, 'R1P31', '0', 31);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(122, 'R2P31', '0.33', 31);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(123, 'R3P31', '0.66', 31);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(124, 'R4P31', '1', 31);

--Domain 4
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (32, 'Operar vários pacotes de software abertos/livres apropriados à área da disciplina, tais como visualizações, análise de dados, simulações e referÍncias on-line', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(125, 'R1P32', '0', 32);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(126, 'R2P32', '0.33', 32);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(127, 'R3P32', '0.66', 32);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(128, 'R4P32', '1', 32);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (33, 'Avaliar a exactidão e utilidade dos recursos da web no apoio à aprendizagem baseada em projetos de uma determinada disciplina', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(129, 'R1P33', '0', 33);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(130, 'R2P33', '0.33', 33);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(131, 'R3P33', '0.66', 33);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(132, 'R4P33', '1', 33);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (34, 'Utilizar um ambiente de criação ou ferramentas tutoriais para elaborar os materiais on-line', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(133, 'R1P34', '0', 34);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(134, 'R2P34', '0.33', 34);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(135, 'R3P34', '0.66', 34);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(136, 'R4P34', '1', 34);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (35, 'Usar uma rede e um programa adequado para gerir, monitorizar e avaliar o progresso de diversos projectos de alunos', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(137, 'R1P35', '0', 35);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(138, 'R2P35', '0.33', 35);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(139, 'R3P35', '0.66', 35);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(140, 'R4P35', '1', 35);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (36, 'Utilizar as TIC para comunicar e colaborar com alunos, colegas, pais e a comunidade em geral, a fim de estimular a aprendizagem do aluno', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(141, 'R1P36', '0', 36);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(142, 'R2P36', '0.33', 36);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(143, 'R3P36', '0.66', 36);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(144, 'R4P36', '1', 36);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (37, 'Usar a Internet para apoiar a colaboração do aluno dentro e fora da sala de aula', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(145, 'R1P37', '0', 37);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(146, 'R2P37', '0.33', 37);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(147, 'R3P37', '0.66', 37);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(148, 'R4P37', '1', 37);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (38, 'Utilizar motores de busca, bases de dados on-line e e-mail para encontrar pessoas e recursos para projetos colaborativos', 10);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(149, 'R1P38', '0', 38);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(150, 'R2P38', '0.33', 38);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(151, 'R3P38', '0.66', 38);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(152, 'R4P38', '1', 38);

--Domain 5
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (39, 'Colocar e organizar os computadores e outros recursos digitais na sala de aula, de modo a apoiar e reforçar as actividades de aprendizagem e interações sociais', 11);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(153, 'R1P39', '0', 39);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(154, 'R2P39', '0.33', 39);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(155, 'R3P39', '0.66', 39);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(156, 'R4P39', '1', 39);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (40, 'Gerenciar as atividades de aprendizagem dos alunos, com base no projeto, num ambiente de tecnologia avançada', 11);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(157, 'R1P40', '0', 40);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(158, 'R2P40', '0.33', 40);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(159, 'R3P40', '0.66', 40);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(160, 'R4P40', '1', 40);

--Domain 6
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (41, 'Usar as TIC para aceder e partilhar recursos em apoio ás suas actividades e ao seu próprio desenvolvimento profissional', 12);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(161, 'R1P41', '0', 41);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(162, 'R2P41', '0.33', 41);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(163, 'R3P41', '0.66', 41);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(164, 'R4P41', '1', 41);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (42, 'Utilizar as TIC para aceder a peritos externos (tutores) e a comunidades de aprendizagem em apoio ás suas atividades e ao seu proprio desenvolvimento profissional', 12);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(165, 'R1P42', '0', 42);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(166, 'R2P42', '0.33', 42);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(167, 'R3P42', '0.66', 42);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(168, 'R4P42', '1', 42);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (43, 'Utilizar as TIC para pesquisar, gerir, analisar, integrar e avaliar as informaÁıes que possam ser usadas para apoiar o seu desenvolvimento profissional', 12);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(169, 'R1P43', '0', 43);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(170, 'R2P43', '0.33', 43);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(171, 'R3P43', '0.66', 43);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(172, 'R4P43', '1', 43);

--##LEVEL 3-'Criação de Conhecimento'
--Domain 1 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (44, 'Capaz de elaborar, implementar e modificar os programas da reforma do ensino ao nível de escola que implementam os elementos-chave das políticas nacionais da reforma do ensino', 13);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(173, 'R1P44', '0', 44);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(174, 'R2P44', '0.33', 44);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(175, 'R3P44', '0.66', 44);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(176, 'R4P44', '1', 44);

--Domain 2 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (45, 'Capaz de identificar e discutir como os alunos aprendem e demonstram competências cognitivas complexas, tais como a gestão de informações, resolução de problemas, colaboração e pensamento crítico', 14);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(177, 'R1P45', '0', 45);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(178, 'R2P45', '0.33', 45);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(179, 'R3P45', '0.66', 45);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(180, 'R4P45', '1', 45);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (46, 'Capaz de ajudar os alunos a utilizarem as TIC para adquirirem as competências de pesquisa, gestão, análise, avaliação e utilização da informação', 14);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(181, 'R1P46', '0', 46);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(182, 'R2P46', '0.33', 46);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(183, 'R3P46', '0.66', 46);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(184, 'R4P46', '1', 46);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (47, 'Capaz de elaborar planificações e atividades de sala de aula que integrem várias ferramentas e dispositivos TIC para ajudar os alunos a adquirirem as competências de raciocínio, planeamento, aprendizagem reflexiva, construção do conhecimento e comunicação', 14);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(185, 'R1P47', '0', 47);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(186, 'R2P47', '0.33', 47);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(187, 'R3P47', '0.66', 47);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(188, 'R4P47', '1', 47);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (48, 'Capaz de ajudar os alunos a utilizarem as TIC para desenvolver competências de comunicação e colaboração', 14);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(189, 'R1P48', '0', 48);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(190, 'R2P48', '0.33', 48);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(191, 'R3P48', '0.66', 48);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(192, 'R4P48', '1', 48);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (49, 'Capaz de ajudar os alunos a desenvolverem regras baseadas em conhecimento e em desempenho e a aplicá-las para avaliar o seu próprio entendimento do assunto principal, assim como de competências em TIC. Ajudar os alunos a usar essas regras para avaliar o trabalho dos outros alunos', 14);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(193, 'R1P49', '0', 49);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(194, 'R2P49', '0.33', 49);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(195, 'R3P49', '0.66', 49);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(196, 'R4P49', '1', 49);

--Domain 3 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (50, 'Simula explicitamente o seu próprio raciocínio, resolução de problemas e criação de conhecimento, enquanto ensinam aos alunos', 15);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(197, 'R1P50', '0', 50);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(198, 'R2P50', '0.33', 50);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(199, 'R3P50', '0.66', 50);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(200, 'R4P50', '1', 50);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (51, 'Elaborar materiais e actividades on-line que envolvam os alunos na solução colaborativa de problemas, pesquisas ou criação artística', 15);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(201, 'R1P51', '0', 51);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(202, 'R2P51', '0.33', 51);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(203, 'R3P51', '0.66', 51);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(204, 'R4P51', '1', 51);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (52, 'Ajudar os alunos a elaborarem materiais e actividades on-line que os envolvam na solução colaborativa de problemas, pesquisas ou criação artística', 15);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(205, 'R1P52', '0', 52);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(206, 'R2P52', '0.33', 52);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(207, 'R3P52', '0.66', 52);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(208, 'R4P52', '1', 52);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (53, 'Ajudar os alunos a incorporarem a produção multimédia, a produção da web e as tecnologias de publicação nos seus projectos, de modo a dar suporte à produção contínua de conhecimento e comunicação com outros públicos', 15);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(209, 'R1P53', '0', 53);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(210, 'R2P53', '0.33', 53);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(211, 'R3P53', '0.66', 53);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(212, 'R4P53', '1', 53);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (54, 'Ajudar os alunos a reflectirem sobre a sua própria aprendizagem', 15);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(213, 'R1P54', '0', 54);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(214, 'R2P54', '0.33', 54);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(215, 'R3P54', '0.66', 54);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(216, 'R4P54', '1', 54);

--Domain 4 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (55, 'Descrever a função e a finalidade das ferramentas e recursos de produção de TIC (gravadora de multimédia e equipamento de produção, ferramentas de edição, programa de publicação, ferramentas de elaboração de web) e usá-las como apoio à inovação e conhecimento dos alunos', 16);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(217, 'R1P55', '0', 55);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(218, 'R2P55', '0.33', 55);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(219, 'R3P55', '0.66', 55);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(220, 'R4P55', '1', 55);

--Domain 5 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (56, 'Descrever a função e a finalidade dos ambientes virtuais e de construção de conhecimento (KBEs) e usá-los para dar suporte ao maior conhecimento e entendimento da disciplina e o desenvolvimento de comunidades de aprendizagem on-line e presenciais', 17);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(221, 'R1P56', '0', 56);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(222, 'R2P56', '0.33', 56);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(223, 'R3P56', '0.66', 56);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(224, 'R4P56', '1', 56);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (57, 'Descrever a função e a finalidade do planeamento e de pensar ferramentas usando-as para apoiar a criação e o planeamento, dos estudantes, das suas próprias actividades de aprendizagem e o seu contínuo pensamento e aprendizagem reflexivos', 17);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(225, 'R1P57', '0', 57);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(226, 'R2P57', '0.33', 57);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(227, 'R3P57', '0.66', 57);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(228, 'R4P57', '1', 57);

--Domain 6 - QUESTIONs
INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (58, 'Desempenhar papel de liderança na criação de uma visão de como a escola seria com as TIC integradas ao currículo e práticas em sala de aula', 18);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(229, 'R1P58', '0', 58);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(230, 'R2P58', '0.33', 58);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(231, 'R3P58', '0.66', 58);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(232, 'R4P58', '1', 58);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (59, 'Desempenhar papel de liderança no apoio à inovação na sua escola e ao aprendizagem contínuo entre os seus colegas', 18);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(233, 'R1P59', '0', 59);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(234, 'R2P59', '0.33', 59);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(235, 'R3P59', '0.66', 59);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(236, 'R4P59', '1', 59);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (60, 'Avaliar continuamente e reflectir sobre a prática profissional para envolvimento na inovação e melhoria contínuas', 18);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(237, 'R1P60', '0', 60);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(238, 'R2P60', '0.33', 60);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(239, 'R3P60', '0.66', 60);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(240, 'R4P60', '1', 60);

INSERT INTO QUESTION (QUESTION_ID, QUESTION, DOMAIN_ID_FK) VALUES (61, 'Usar os recursos de TIC para participar nas comunidades profissionais e partilhar e discutir as melhores práticas de ensino', 18);
--RESPONSES
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(241, 'R1P61', '0', 61);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(242, 'R2P61', '0.33', 61);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(243, 'R3P61', '0.66', 61);
INSERT INTO RESPONSE(RESPONSE_ID, RESPONSE, VALUE, QUESTION_ID_FK) VALUES(244, 'R4P61', '1', 61);

--INSERT INTO REGION (REGION_ID, NAME) VALUES(1, 'Amarante');
--INSERT INTO REGION (REGION_ID, NAME) VALUES(2, 'Porto');
INSERT INTO REGION (REGION_ID, NAME) VALUES(164, 'Abrantes (1401)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(80, 'Águeda (0101)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(140, 'Aguiar da Beira (0901)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(216, 'Alandroal (0701)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(81, 'Albergaria-a-Velha (0102)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(263, 'Albufeira (0801)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(217, 'Alcácer do Sal (1501)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(165, 'Alcanena (1402)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(166, 'Alcobaça (1001)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(199, 'Alcochete (1502)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(264, 'Alcoutim (0802)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(167, 'Alenquer (1101)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(43, 'Alfândega da Fé (0401)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(44, 'Alijó (1701)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(265, 'Aljezur (0803)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(246, 'Aljustrel (0201)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(200, 'Almada (1503)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(141, 'Almeida (0902)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(168, 'Almeirim (1403)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(247, 'Almodôvar (0202)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(169, 'Alpiarça (1404)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(218, 'Alter do Chão (1201)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(113, 'Alvaiázere (1002)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(248, 'Alvito (0203)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(201, 'Amadora (1115)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(1, 'Amarante (1301)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(2, 'Amares (0301)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(82, 'Anadia (0103)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(114, 'Ansião (1003)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(3, 'Arcos de Valdevez (1601)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(115, 'Arganil (0601)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(45, 'Armamar (1801)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(83, 'Arouca (0104)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(219, 'Arraiolos (0702)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(220, 'Arronches (1202)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(170, 'Arruda dos Vinhos (1102)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(84, 'Aveiro (0105)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(221, 'Avis (1203)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(171, 'Azambuja (1103)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(4, 'Baião (1302)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(5, 'Barcelos (0302)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(249, 'Barrancos (0204)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(202, 'Barreiro (1504)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(116, 'Batalha (1004)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(250, 'Beja (0205)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(142, 'Belmonte (0501)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(172, 'Benavente (1405)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(173, 'Bombarral (1005)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(222, 'Borba (0703)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(46, 'Boticas (1702)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(6, 'Braga (0303)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(47, 'Bragança (0402)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(7, 'Cabeceiras de Basto (0304)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(174, 'Cadaval (1104)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(175, 'Caldas da Rainha (1006)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(8, 'Caminha (1602)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(223, 'Campo Maior (1204)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(117, 'Cantanhede (0602)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(48, 'Carrazeda de Ansiães (0403)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(85, 'Carregal do Sal (1802)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(176, 'Cartaxo (1406)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(203, 'Cascais (1105)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(118, 'Castanheira de Pêra (1007)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(143, 'Castelo Branco (0502)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(86, 'Castelo de Paiva (0106)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(224, 'Castelo de Vide (1205)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(87, 'Castro Daire (1803)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(266, 'Castro Marim (0804)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(251, 'Castro Verde (0206)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(144, 'Celorico da Beira (0903)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(9, 'Celorico de Basto (0305)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(177, 'Chamusca (1407)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(49, 'Chaves (1703)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(50, 'Cinfães (1804)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(119, 'Coimbra (0603)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(120, 'Condeixa-a-Nova (0604)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(178, 'Constância (1408)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(179, 'Coruche (1409)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(145, 'Covilhã (0503)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(225, 'Crato (1206)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(252, 'Cuba (0207)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(226, 'Elvas (1207)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(180, 'Entroncamento (1410)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(88, 'Espinho (0107)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(10, 'Esposende (0306)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(89, 'Estarreja (0108)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(227, 'Estremoz (0704)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(228, 'Évora (0705)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(11, 'Fafe (0307)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(267, 'Faro (0805)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(12, 'Felgueiras (1303)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(253, 'Ferreira do Alentejo (0208)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(181, 'Ferreira do Zêzere (1411)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(121, 'Figueira da Foz (0605)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(146, 'Figueira de Castelo Rodrigo (0904)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(122, 'Figueiró dos Vinhos (1008)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(147, 'Fornos de Algodres (0905)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(51, 'Freixo de Espada à Cinta (0404)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(229, 'Fronteira (1208)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(148, 'Fundão (0504)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(230, 'Gavião (1209)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(123, 'Góis (0606)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(182, 'Golegã (1412)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(13, 'Gondomar (1304)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(149, 'Gouveia (0906)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(254, 'Grândola (1505)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(150, 'Guarda (0907)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(14, 'Guimarães (0308)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(151, 'Idanha-a-Nova (0505)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(90, 'Ílhavo (0110)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(268, 'Lagoa (0806)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(269, 'Lagos (0807)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(52, 'Lamego (1805)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(124, 'Leiria (1009)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(204, 'Lisboa (1106)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(270, 'Loulé (0808)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(205, 'Loures (1107)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(183, 'Lourinhã (1108)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(125, 'Lousã (0607)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(15, 'Lousada (1305)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(184, 'Mação (1413)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(53, 'Macedo de Cavaleiros (0405)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(185, 'Mafra (1109)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(16, 'Maia (1306)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(91, 'Mangualde (1806)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(152, 'Manteigas (0908)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(17, 'Marco de Canaveses (1307)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(126, 'Marinha Grande (1010)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(231, 'Marvão (1210)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(18, 'Matosinhos (1308)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(92, 'Mealhada (0111)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(153, 'Meda (0909)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(19, 'Melgaço (1603)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(255, 'Mértola (0209)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(54, 'Mesão Frio (1704)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(127, 'Mira (0608)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(128, 'Miranda do Corvo (0609)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(55, 'Miranda do Douro (0406)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(56, 'Mirandela (0407)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(57, 'Mogadouro (0408)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(58, 'Moimenta da Beira (1807)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(206, 'Moita (1506)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(20, 'Monção (1604)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(271, 'Monchique (0809)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(59, 'Mondim de Basto (1705)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(232, 'Monforte (1211)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(60, 'Montalegre (1706)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(233, 'Montemor-o-Novo (0706)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(129, 'Montemor-o-Velho (0610)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(207, 'Montijo (1507)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(234, 'Mora (0707)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(93, 'Mortágua (1808)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(256, 'Moura (0210)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(235, 'Mourão (0708)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(61, 'Murça (1707)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(94, 'Murtosa (0112)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(186, 'Nazaré (1011)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(95, 'Nelas (1809)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(236, 'Nisa (1212)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(187, 'Óbidos (1012)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(257, 'Odemira (0211)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(208, 'Odivelas (1116)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(209, 'Oeiras (1110)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(154, 'Oleiros (0506)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(272, 'Olhão (0810)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(96, 'Oliveira de Azeméis (0113)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(97, 'Oliveira de Frades (1810)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(98, 'Oliveira do Bairro (0114)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(130, 'Oliveira do Hospital (0611)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(188, 'Ourém (1421)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(258, 'Ourique (0212)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(99, 'Ovar (0115)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(21, 'Paços de Ferreira (1309)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(210, 'Palmela (1508)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(131, 'Pampilhosa da Serra (0612)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(22, 'Paredes (1310)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(23, 'Paredes de Coura (1605)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(132, 'Pedrógão Grande (1013)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(133, 'Penacova (0613)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(24, 'Penafiel (1311)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(100, 'Penalva do Castelo (1811)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(155, 'Penamacor (0507)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(62, 'Penedono (1812)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(134, 'Penela (0614)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(189, 'Peniche (1014)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(63, 'Peso da Régua (1708)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(156, 'Pinhel (0910)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(135, 'Pombal (1015)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(25, 'Ponte da Barca (1606)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(26, 'Ponte de Lima (1607)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(237, 'Ponte de Sor (1213)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(238, 'Portalegre (1214)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(239, 'Portel (0709)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(273, 'Portimão (0811)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(27, 'Porto (1312)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(136, 'Porto de Mós (1016)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(28, 'Póvoa de Lanhoso (0309)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(29, 'Póvoa de Varzim (1313)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(157, 'Proença-a-Nova (0508)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(240, 'Redondo (0710)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(241, 'Reguengos de Monsaraz (0711)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(64, 'Resende (1813)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(65, 'Ribeira de Pena (1709)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(190, 'Rio Maior (1414)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(66, 'Sabrosa (1710)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(158, 'Sabugal (0911)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(191, 'Salvaterra de Magos (1415)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(101, 'Santa Comba Dão (1814)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(102, 'Santa Maria da Feira (0109)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(67, 'Santa Marta de Penaguião (1711)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(192, 'Santarém (1416)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(259, 'Santiago do Cacém (1509)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(30, 'Santo Tirso (1314)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(274, 'São Brás de Alportel (0812)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(103, 'São João da Madeira (0116)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(68, 'São João da Pesqueira (1815)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(104, 'São Pedro do Sul (1816)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(193, 'Sardoal (1417)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(105, 'Sátão (1817)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(159, 'Seia (0912)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(211, 'Seixal (1510)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(69, 'Sernancelhe (1818)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(260, 'Serpa (0213)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(160, 'Sertã (0509)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(212, 'Sesimbra (1511)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(213, 'Setúbal (1512)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(106, 'Sever do Vouga (0117)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(275, 'Silves (0813)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(261, 'Sines (1513)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(214, 'Sintra (1111)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(194, 'Sobral de Monte Agraço (1112)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(137, 'Soure (0615)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(242, 'Sousel (1215)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(138, 'Tábua (0616)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(70, 'Tabuaço (1819)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(71, 'Tarouca (1820)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(276, 'Tavira (0814)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(31, 'Terras de Bouro (0310)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(195, 'Tomar (1418)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(107, 'Tondela (1821)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(72, 'Torre de Moncorvo (0409)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(196, 'Torres Novas (1419)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(197, 'Torres Vedras (1113)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(161, 'Trancoso (0913)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(32, 'Trofa (1318)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(108, 'Vagos (0118)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(109, 'Vale de Cambra (0119)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(33, 'Valença (1608)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(34, 'Valongo (1315)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(73, 'Valpaços (1712)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(243, 'Vendas Novas (0712)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(244, 'Viana do Alentejo (0713)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(35, 'Viana do Castelo (1609)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(262, 'Vidigueira (0214)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(36, 'Vieira do Minho (0311)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(162, 'Vila de Rei (0510)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(277, 'Vila do Bispo (0815)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(37, 'Vila do Conde (1316)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(74, 'Vila Flor (0410)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(215, 'Vila Franca de Xira (1114)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(198, 'Vila Nova da Barquinha (1420)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(38, 'Vila Nova de Cerveira (1610)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(39, 'Vila Nova de Famalicão (0312)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(75, 'Vila Nova de Foz Côa (0914)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(40, 'Vila Nova de Gaia (1317)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(110, 'Vila Nova de Paiva (1822)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(139, 'Vila Nova de Poiares (0617)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(76, 'Vila Pouca de Aguiar (1713)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(77, 'Vila Real (1714)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(278, 'Vila Real de Santo António (0816)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(163, 'Vila Velha de Ródão (0511)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(41, 'Vila Verde (0313)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(245, 'Vila Viçosa (0714)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(78, 'Vimioso (0411)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(79, 'Vinhais (0412)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(111, 'Viseu (1823)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(42, 'Vizela (0314)');
INSERT INTO REGION (REGION_ID, NAME) VALUES(112, 'Vouzela (1824)');

INSERT INTO SCHOOL (SCHOOL_ID, NAME, REGION_ID_FK) VALUES(1, 'Escola Básica de Amarante', 1);
INSERT INTO SCHOOL (SCHOOL_ID, NAME, REGION_ID_FK) VALUES(2, 'Escola Secundária de Amarante', 1);
INSERT INTO SCHOOL (SCHOOL_ID, NAME, REGION_ID_FK) VALUES(3, 'Escola Básica do Viso', 2);
